[toolchain]
channel = "stable"
components = [
  "cargo",
  "clippy",
  "rust-analyzer",
  "rust-src",
  "rustc",
  "rustfmt",
]
targets = [
  "wasm32-unknown-unknown",
  "wasm32-wasip1",
  "x86_64-pc-windows-gnu",
  "x86_64-unknown-linux-gnu",
  "aarch64-unknown-linux-gnu",
  "x86_64-unknown-linux-musl",
]
profile = "default"
